[package]
name = "digits"
version = "2.0.0"
authors = ["Daniel P. Clark <6ftdan@gmail.com>"]
edition = "2021"
rust-version = "1.56"
description = "Custom “numeric” incrementor without u64 MAX limit in size. Like a score flipper for a custom character set."
documentation = "https://docs.rs/digits"
homepage = "https://github.com/danielpclark/digits"
repository = "https://github.com/danielpclark/digits"
license = "MIT OR Apache-2.0"
readme = "README.md"
keywords = ["numeric","base","conversion","decimal"]
categories = ["cryptography", "data-structures"]

[dependencies]
base_custom = "0.2"
